# Generated by Django 4.2.1 on 2023-05-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knitpro', '0002_yarn_knit_yarn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knit',
            name='yarn',
        ),
        migrations.AddField(
            model_name='knit',
            name='yarns',
            field=models.ManyToManyField(related_name='knits', to='knitpro.yarn'),
        ),
    ]
