# Generated by Django 4.2.1 on 2023-05-28 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knitpro', '0003_remove_knit_yarn_knit_yarns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=150)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='yarn',
            name='brand',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Knit',
        ),
        migrations.AddField(
            model_name='yarn',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='knitpro.project'),
        ),
    ]
