# Generated by Django 4.2.1 on 2023-05-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knitpro', '0004_project_alter_yarn_brand_alter_yarn_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarn',
            name='weight',
            field=models.CharField(max_length=20),
        ),
    ]
