# Generated by Django 4.2.1 on 2023-05-29 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knitpro', '0006_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarn',
            name='brand',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knitpro.project'),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='weight',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
